### ISSUE TITLE
Second USB Input to wake from sleep

### ISSUE THREAD

**Issue by MPC561** [tspng/gigabyte-z390-m-gaming-opencore#1]
For me it helped to set darkwake=8 within the bootarguments.
Might have an impact on powernap then.

**Comment by tspng** [comment]
@MPC561, Thanks for the hint. 
I have to look into darkwake. But AFAIK a value of 8 (and 10 for that matter) should be obsolete since macOS Catalina, as explained here: https://www.insanelymac.com/forum/topic/342002-darkwake-on-macos-catalina-boot-args-darkwake8-darkwake10-are-obsolete/
Does it really make a difference in your system?

**Comment by MPC561** [comment]
I need to say: "You are right". Just tested it again and it is obsolete, I do not have the second click issue without darkwake in the bootarguments.

But maybe as axplanation. I introduced it with Mojave and Clover and there it solved my problems. But before I had in a german hackintosh forum a discussion with another guy with more or less the same system (Motherboard and CPU) but another graphic card (me at this time a Gigabyte AMD RX580). Hi had not the problem without using darkwake and for me it solved the problem.

Greets and sorry,
MPC561
